### ISSUE TITLE
How to visualize the attention

### ISSUE THREAD

**Issue by taineleau** [FactoDeepLearning/DAN#12]
Hi, I sucessfully reproduce your paper results! It's an amazing work!
From your paper Fig. 5, you mentioned `Attention weights are colored given the last predicted layout token.`

Could you provide the visualization code? If not, could you briefly list the steps to visualize the weights? e.g. which layer(s) are you using, how did you compute the final rendering.

Thank you!

**Comment by FactoDeepLearning** [comment]
Attention weights are from the cross attention of the last transformer layer.
Prediction is split into text chunks with associate weights given predicted layout tokens, and a dedicated color is used for each one.
Weights are projected onto the input image using matplotlib without interpolation: image first, then weights of each chunk with extent option and corresponding color.

**Comment by taineleau** [comment]
Thank you! that's useful!

**Comment by chrisgwe** [comment]
hey, how are you Taineleau, when you reproduce this work have you faceing the 'valid_fonts': [] is empty this issue, could you tell me how to deal with 
<img width="1624" alt="image" src="https://github.com/FactoDeepLearning/DAN/assets/123208317/2846ee59-5fe6-4d0a-85da-79c2cbcb2565">
