### ISSUE TITLE
'valid_fonts': [] is empty 

### ISSUE THREAD

**Issue by chrisgwe** [FactoDeepLearning/DAN#15]
how should I do in the list fonts, or any advice? thank you!
![unnamed](https://github.com/FactoDeepLearning/DAN/assets/123208317/7e743981-2ff0-48ed-8d10-819a99996868)
![unnamed](https://github.com/FactoDeepLearning/DAN/assets/123208317/a4937021-b102-489f-9189-162698e9b74b)

**Comment by FactoDeepLearning** [comment]
Hi, you must add some .ttf files in the "Fonts" folder. You cannot generate synthetic text without any font. Your image corresponds to the list of fonts we used in the paper.

**Comment by chrisgwe** [comment]
I just wonder where can I get for those .ttf files for the "Fonts" folder, thank you

**Comment by FactoDeepLearning** [comment]
We do not have rights to share them. Just check on google to download some of them.

**Comment by chrisgwe** [comment]
sorry, I added them in the fonts folder but here is the result still the same error
<img width="1009" alt="image" src="https://github.com/FactoDeepLearning/DAN/assets/123208317/a31d5ec6-9c2a-45a5-8e2e-53695f5e1be7">
<img width="128" alt="image" src="https://github.com/FactoDeepLearning/DAN/assets/123208317/fd3984b2-7332-46f7-b77a-db906ac6fd9a">
