### ISSUE TITLE
Implementation of curriculum learning

### ISSUE THREAD

**Issue by noobpeng99** [FactoDeepLearning/DAN#17]
Hello！

Thank you for your sharing.

I noticed that there is no code related to curriculum learning provided in the repository.

In particular, it seems that the methods init_curriculum(), check_and_update_curriculum(), and update_curriculum_model() in the GenericTrainingManager class are not implemented anywhere.

This could be the reason for my failure in READ 2016.

Can you provide me with some improvement suggestions?

**Comment by FactoDeepLearning** [comment]
Curriculum learning is handled through the synthetic document generation process
https://github.com/FactoDeepLearning/DAN/blob/da3046a1cc83e9be3e54dd31a5e74d6134d1ebdc/OCR/ocr_dataset_manager.py#L148C26-L148C50

The functions you mentioned are not used, but this is expected

**Comment by noobpeng99** [comment]
> Curriculum learning is handled through the synthetic document generation process https://github.com/FactoDeepLearning/DAN/blob/da3046a1cc83e9be3e54dd31a5e74d6134d1ebdc/OCR/ocr_dataset_manager.py#L148C26-L148C50
> 
> The functions you mentioned are not used, but this is expected

Thank you for your response. That's exactly what I was looking for.
