### ISSUE TITLE
Installation issues in fresh install

### ISSUE THREAD

**Issue by Jordy-VL** [FactoDeepLearning/DAN#3]
## issues installing

`  __main__.RequiredDependencyException: pangocairo >= 1.30.0 is required`

Solved by: 
https://github.com/ManimCommunity/ManimPango/issues/53
`sudo apt-get install libsdl-pango-dev`

```
ERROR: No matching distribution found for masked-norm==0.0.0
ERROR: No matching distribution found for pkg_resources==0.0.0
```

I just removed the last two packages from requirements.

**Comment by FactoDeepLearning** [comment]
Thank you, it has been updated.
