### ISSUE TITLE
share font files

### ISSUE THREAD

**Issue by Jordy-VL** [FactoDeepLearning/DAN#5]
Hi, 

Could you share your font files for step 3? 

"Step 3: Add any font you want as .ttf file in the folder Fonts"

This allows easy reproducibility. 

Kind regards!

**Comment by Jordy-VL** [comment]
For example, I installed "Lato-HairlineItalic.ttf".
yet some of the alphabet characters are not in there and as such get deleted from the synthetic line generation process.

`                        if not char_in_font(char, font_path):  [line 1022]
`
If I have the exact font files, I will have closer to exact reproduction :) Thanks!

**Comment by FactoDeepLearning** [comment]
Hi, I don't think I have rights to distribute those font files. I will check if there are additional information (such as font version)  I can add to avoid this issue

**Comment by FactoDeepLearning** [comment]
I've added font version in the font list files for your reproducibility issue.
