### ISSUE TITLE
Question about number of training epochs

### ISSUE THREAD

**Issue by J-L-O** [FactoDeepLearning/DAN#6]
Hi, thank you for publishing the code for your paper.

I have a question about the way the training epochs are specified in the code. 
Since there are two criteria for deciding when to terminate training, I'm not quite sure how to best replicate your results.
Especially the time-limit makes it hard to tell how long the training ran in practice, because on different hardware the time limit will hit at different epochs.
Did you always run the training for `max_nb_epochs` , or did the time-limit result in early stopping?
If the latter is the case, do you remember how many epochs you trained for in practice?

Thank you!

**Comment by FactoDeepLearning** [comment]
Hi, you are right. Time was the stopping criteria (4 days in total per training). It corresponds to ~1300 epochs for RIMES 2009, ~3900 epochs for READ 2016 (single page) and ~4400 epochs for READ 2016 (double-page).

**Comment by FactoDeepLearning** [comment]
Yes, 2 days corresponded to ~3600 epochs for READ 2016 and  ~700 epochs for RIMES 2009

**Comment by J-L-O** [comment]
Awesome, thanks a lot for the swift response!
